import type {
  CliCapabilityMatrixEntry,
  CliCommandDefinition,
  CliConfirmationRule,
  CliContractValidationIssue,
  CliErrorCatalogEntry,
  CliErrorCode,
  CliExitCode,
  CliExitCodeClassDefinition,
  SourceCapabilityIssue,
} from './types';

export const CLI_CONTRACT_VERSION = '2026-05-10.v1';
export const CLI_RESULT_SCHEMA_VERSION = '1.0.0';

export const REQUIRED_CAPABILITY_SOURCE_ISSUES: readonly SourceCapabilityIssue[] = [
  'VIT-46',
  'VIT-47',
  'VIT-48',
  'VIT-49',
  'VIT-50',
  'VIT-77',
];

export const CLI_COMMANDS: readonly CliCommandDefinition[] = [
  {
    id: 'workspace.open',
    group: 'workspace-file',
    displayName: 'Open workspace',
    description: 'Open a known workspace path and return the workspace snapshot.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'WorkspaceSession',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.create',
    group: 'workspace-file',
    displayName: 'Create workspace',
    description: 'Create a workspace at an explicit path and return the workspace snapshot.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'WorkspaceSession',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.files.list',
    group: 'workspace-file',
    displayName: 'List workspace files',
    description: 'Return Markdown files in the active workspace.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'WorkspaceFile[]',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.file.create',
    group: 'workspace-file',
    displayName: 'Create Markdown file',
    description: 'Create a workspace-relative Markdown file with optional initial content.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'DocumentSnapshot',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.file.open',
    group: 'workspace-file',
    displayName: 'Open Markdown file',
    description: 'Read a workspace-relative Markdown file and return its current snapshot.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'DocumentSnapshot',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.file.save',
    group: 'workspace-file',
    displayName: 'Save Markdown file',
    description: 'Write Markdown through the guarded save lifecycle with version checks.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'SaveResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'workspace.file.rename',
    group: 'workspace-file',
    displayName: 'Rename Markdown file',
    description: 'Rename a workspace-relative Markdown file after collision and version checks.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'RenameDocumentResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['destructive_file'],
  },
  {
    id: 'workspace.file.delete',
    group: 'workspace-file',
    displayName: 'Delete Markdown file',
    description: 'Delete a workspace-relative Markdown file after explicit confirmation.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'DeleteDocumentResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['destructive_file'],
  },
  {
    id: 'mindmap.read',
    group: 'mindmap',
    displayName: 'Read mind map',
    description: 'Return nodes, links, collapsed state, and diagnostics for a document.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'MindMapDocument',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'mindmap.node.add',
    group: 'mindmap',
    displayName: 'Add node',
    description: 'Add a child or sibling node through the same domain command contract as the UI.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'mindmap.node.update',
    group: 'mindmap',
    displayName: 'Update node',
    description: 'Update node text through the domain command contract.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'mindmap.branch.move',
    group: 'mindmap',
    displayName: 'Move branch',
    description: 'Move a branch after cycle checks and explicit confirmation.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['destructive_mindmap'],
  },
  {
    id: 'mindmap.branch.delete',
    group: 'mindmap',
    displayName: 'Delete branch',
    description: 'Delete a node subtree after explicit confirmation.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['destructive_mindmap'],
  },
  {
    id: 'mindmap.history.undo',
    group: 'mindmap',
    displayName: 'Undo mind map change',
    description: 'Undo a persisted editor command when the command history is available.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'mindmap.history.redo',
    group: 'mindmap',
    displayName: 'Redo mind map change',
    description: 'Redo a persisted editor command when the command history is available.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'MindMapCommandResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'markdown.parse',
    group: 'markdown',
    displayName: 'Parse Markdown',
    description: 'Parse headings, nested lists, links, and compatibility diagnostics.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'ParseMarkdownPreviewResult',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'markdown.serialize',
    group: 'markdown',
    displayName: 'Serialize mind map',
    description: 'Serialize a mind map into deterministic Markmap-compatible Markdown.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'SerializeMindMapResult',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'markdown.links.resolve',
    group: 'markdown',
    displayName: 'Resolve Markdown link',
    description: 'Resolve a standard Markdown link or Obsidian-style wikilink in workspace scope.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'LinkResolution',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'markdown.links.create-target',
    group: 'markdown',
    displayName: 'Create link target',
    description: 'Create a missing Markdown link target after explicit user confirmation.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'DocumentSnapshot',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['destructive_file'],
  },
  {
    id: 'ai.context.preview',
    group: 'ai',
    displayName: 'Preview AI context',
    description: 'Build the bounded context snapshot that would be sent to an AI provider.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'AiContextSnapshot',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'ai.chat.send',
    group: 'ai',
    displayName: 'Send AI chat message',
    description: 'Run a configured local AI provider with an immutable context snapshot.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'AiResponse',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'ai.proposal.validate',
    group: 'ai',
    displayName: 'Validate AI proposal',
    description: 'Validate a normalized AI change proposal without mutating the document.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'ProposalValidationResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'ai.proposal.apply',
    group: 'ai',
    displayName: 'Apply AI proposal',
    description: 'Apply a validated proposal after confirmation and current-version preflight.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'ApplyProposalResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['ai_apply', 'multi_file_change'],
  },
  {
    id: 'git.status',
    group: 'git',
    displayName: 'Show Git status',
    description: 'Return normalized Git repository and workspace-relative change state.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'GitStatusSummary',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'git.init',
    group: 'git',
    displayName: 'Enable Git',
    description: 'Initialize Git metadata for the workspace after explicit confirmation.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'GitRepositoryState',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['git_init'],
  },
  {
    id: 'git.snapshot',
    group: 'git',
    displayName: 'Create Git snapshot',
    description: 'Stage eligible workspace changes and create a local commit snapshot.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'GitSnapshotResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['git_snapshot'],
  },
  {
    id: 'git.history',
    group: 'git',
    displayName: 'Show Git history',
    description: 'Return workspace or file history entries without mutating repository state.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'GitHistoryEntry[]',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'git.diff',
    group: 'git',
    displayName: 'Show Git diff',
    description: 'Return structured Markdown-oriented diff data with truncation metadata.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'GitDiffResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'git.restore',
    group: 'git',
    displayName: 'Restore Git file',
    description: 'Restore a historical file version as a new working-tree change.',
    disposition: 'cli_supported_with_confirmation',
    outputDataKind: 'GitRestoreResult',
    requiresWorkspace: true,
    supportsJsonOutput: true,
    confirmationKinds: ['git_restore'],
  },
  {
    id: 'ui.open',
    group: 'desktop-ui',
    displayName: 'Open desktop UI',
    description: 'Open or wake the desktop app at the active workspace or document.',
    disposition: 'cli_wakes_desktop_ui',
    outputDataKind: 'CliUiAction',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'ui.focus',
    group: 'desktop-ui',
    displayName: 'Focus desktop UI',
    description: 'Focus a node, file, link diagnostic, or Git/AI review surface in the app.',
    disposition: 'cli_wakes_desktop_ui',
    outputDataKind: 'CliUiAction',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'ui.review',
    group: 'desktop-ui',
    displayName: 'Open review surface',
    description: 'Open UI for ambiguous, lossy, multi-file, or conflict-heavy decisions.',
    disposition: 'cli_wakes_desktop_ui',
    outputDataKind: 'CliUiAction',
    requiresWorkspace: true,
    supportsJsonOutput: true,
  },
  {
    id: 'diagnostics.doctor',
    group: 'diagnostics',
    displayName: 'Run diagnostics',
    description: 'Check workspace, parser, AI provider, Git, and desktop integration health.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'DiagnosticReport',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'help',
    group: 'diagnostics',
    displayName: 'Show help',
    description: 'Render human-readable command help.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'HelpText',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
  {
    id: 'contract.print',
    group: 'diagnostics',
    displayName: 'Print CLI contract',
    description: 'Print the machine-readable CLI capability and result contract.',
    disposition: 'headless_cli_supported',
    outputDataKind: 'CliContract',
    requiresWorkspace: false,
    supportsJsonOutput: true,
  },
];

export const CLI_CAPABILITY_MATRIX: readonly CliCapabilityMatrixEntry[] = [
  {
    capabilityId: 'vit46-mindmap-query',
    sourceIssue: 'VIT-46',
    capabilityGroup: 'Mind map document inspection',
    disposition: 'headless_cli_supported',
    commandIds: ['mindmap.read'],
    rationale: 'Reading normalized document structure is deterministic and does not need canvas state.',
  },
  {
    capabilityId: 'vit46-mindmap-safe-edit',
    sourceIssue: 'VIT-46',
    capabilityGroup: 'Non-destructive node editing',
    disposition: 'headless_cli_supported',
    commandIds: ['mindmap.node.add', 'mindmap.node.update', 'mindmap.history.undo', 'mindmap.history.redo'],
    rationale: 'Pure domain commands can run headlessly when version and target ids are supplied.',
  },
  {
    capabilityId: 'vit46-mindmap-destructive-edit',
    sourceIssue: 'VIT-46',
    capabilityGroup: 'Branch move and delete',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['mindmap.branch.move', 'mindmap.branch.delete'],
    rationale: 'Branch movement and deletion can remove or relocate large subtrees.',
  },
  {
    capabilityId: 'vit46-canvas-navigation',
    sourceIssue: 'VIT-46',
    capabilityGroup: 'Canvas focus, pan, zoom, and selection presentation',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.open', 'ui.focus'],
    rationale: 'Canvas navigation is inherently visual and belongs in the desktop surface.',
  },
  {
    capabilityId: 'vit46-high-frequency-input',
    sourceIssue: 'VIT-46',
    capabilityGroup: 'Keyboard and mouse editing gestures',
    disposition: 'intentionally_unsupported',
    commandIds: [],
    rationale: 'The CLI exposes command effects, not a replacement for interactive editing gestures.',
  },
  {
    capabilityId: 'vit47-workspace-lifecycle',
    sourceIssue: 'VIT-47',
    capabilityGroup: 'Workspace open, create, restore, and file listing',
    disposition: 'headless_cli_supported',
    commandIds: ['workspace.open', 'workspace.create', 'workspace.files.list'],
    rationale: 'Explicit paths and workspace ids can be validated without UI picker dialogs.',
  },
  {
    capabilityId: 'vit47-file-read-write',
    sourceIssue: 'VIT-47',
    capabilityGroup: 'Markdown create, open, and guarded save',
    disposition: 'headless_cli_supported',
    commandIds: ['workspace.file.create', 'workspace.file.open', 'workspace.file.save'],
    rationale: 'Path guard, version checks, and atomic save can return structured envelopes.',
  },
  {
    capabilityId: 'vit47-file-destructive-lifecycle',
    sourceIssue: 'VIT-47',
    capabilityGroup: 'Markdown rename and delete',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['workspace.file.rename', 'workspace.file.delete'],
    rationale: 'Rename and delete are explicit filesystem mutations and must not be silent.',
  },
  {
    capabilityId: 'vit47-dirty-conflict-resolution',
    sourceIssue: 'VIT-47',
    capabilityGroup: 'Unsaved changes and external conflict decisions',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.review'],
    rationale: 'Multi-choice conflict prompts are UI-owned unless a command supplies a confirmation token.',
  },
  {
    capabilityId: 'vit48-markdown-compatibility',
    sourceIssue: 'VIT-48',
    capabilityGroup: 'Markdown parse, serialize, and diagnostics',
    disposition: 'headless_cli_supported',
    commandIds: ['markdown.parse', 'markdown.serialize'],
    rationale: 'Parser and serializer contracts are pure and fixture-driven.',
  },
  {
    capabilityId: 'vit48-link-resolution',
    sourceIssue: 'VIT-48',
    capabilityGroup: 'Obsidian and Markdown link resolution',
    disposition: 'headless_cli_supported',
    commandIds: ['markdown.links.resolve'],
    rationale: 'Resolving links returns deterministic resolved, unresolved, ambiguous, or unsafe results.',
  },
  {
    capabilityId: 'vit48-link-target-creation',
    sourceIssue: 'VIT-48',
    capabilityGroup: 'Create missing Markdown link targets',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['markdown.links.create-target'],
    rationale: 'Creating a target file is a workspace mutation and requires confirmation.',
  },
  {
    capabilityId: 'vit48-ambiguous-lossy-review',
    sourceIssue: 'VIT-48',
    capabilityGroup: 'Ambiguous links and lossy Markdown save review',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.review'],
    rationale: 'Ambiguous choices and lossy-save review need a user-facing decision surface.',
  },
  {
    capabilityId: 'vit48-full-obsidian-plugin-ecosystem',
    sourceIssue: 'VIT-48',
    capabilityGroup: 'Full Obsidian plugin, Dataview, Canvas, and non-Markdown imports',
    disposition: 'intentionally_unsupported',
    commandIds: [],
    rationale: 'The product scope supports a documented Markdown and wikilink subset only.',
  },
  {
    capabilityId: 'vit49-ai-context',
    sourceIssue: 'VIT-49',
    capabilityGroup: 'Bounded AI context preview',
    disposition: 'headless_cli_supported',
    commandIds: ['ai.context.preview'],
    rationale: 'The context snapshot is immutable, size-bounded, and can be returned before provider calls.',
  },
  {
    capabilityId: 'vit49-ai-chat',
    sourceIssue: 'VIT-49',
    capabilityGroup: 'Local AI chat execution',
    disposition: 'headless_cli_supported',
    commandIds: ['ai.chat.send'],
    rationale: 'Chat can run headlessly when provider config is valid and context scope is explicit.',
  },
  {
    capabilityId: 'vit49-provider-configuration-ui',
    sourceIssue: 'VIT-49',
    capabilityGroup: 'Provider setup and authentication recovery',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.open', 'ui.review'],
    rationale: 'Provider setup may require local auth, path selection, and guided recovery.',
  },
  {
    capabilityId: 'vit50-proposal-validation',
    sourceIssue: 'VIT-50',
    capabilityGroup: 'AI proposal validation and impact summary',
    disposition: 'headless_cli_supported',
    commandIds: ['ai.proposal.validate'],
    rationale: 'Proposal validation is pure and must not mutate editor or file state.',
  },
  {
    capabilityId: 'vit50-proposal-apply',
    sourceIssue: 'VIT-50',
    capabilityGroup: 'AI proposal apply',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['ai.proposal.apply'],
    rationale: 'AI apply changes user content and must require confirmation and version preflight.',
  },
  {
    capabilityId: 'vit50-proposal-review',
    sourceIssue: 'VIT-50',
    capabilityGroup: 'Proposal visual review and multi-file risk review',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.review'],
    rationale: 'Visual diff and risk review remain desktop surfaces.',
  },
  {
    capabilityId: 'vit50-auto-apply',
    sourceIssue: 'VIT-50',
    capabilityGroup: 'AI automatic workspace rewrite',
    disposition: 'intentionally_unsupported',
    commandIds: [],
    rationale: 'AI must not rewrite files or the workspace without review and confirmation.',
  },
  {
    capabilityId: 'vit77-git-read',
    sourceIssue: 'VIT-77',
    capabilityGroup: 'Git status, history, and diff',
    disposition: 'headless_cli_supported',
    commandIds: ['git.status', 'git.history', 'git.diff'],
    rationale: 'Read-only repository operations can return structured data without UI.',
  },
  {
    capabilityId: 'vit77-git-mutating-safe',
    sourceIssue: 'VIT-77',
    capabilityGroup: 'Git init and snapshot',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['git.init', 'git.snapshot'],
    rationale: 'Initializing metadata and creating commits are user-visible repository mutations.',
  },
  {
    capabilityId: 'vit77-git-restore',
    sourceIssue: 'VIT-77',
    capabilityGroup: 'Restore historical file content',
    disposition: 'cli_supported_with_confirmation',
    commandIds: ['git.restore'],
    rationale: 'Restore rewrites working-tree content and must become a confirmed new change.',
  },
  {
    capabilityId: 'vit77-git-conflict-review',
    sourceIssue: 'VIT-77',
    capabilityGroup: 'Merge conflict, detached state, and restore conflict review',
    disposition: 'cli_wakes_desktop_ui',
    commandIds: ['ui.review'],
    rationale: 'Complex repository states require guided review rather than blind automation.',
  },
  {
    capabilityId: 'vit77-remote-git',
    sourceIssue: 'VIT-77',
    capabilityGroup: 'Remote push, pull, branch collaboration, rebase, submodules, and LFS',
    disposition: 'intentionally_unsupported',
    commandIds: [],
    rationale: 'First CLI contract is local workspace versioning only.',
  },
  {
    capabilityId: 'vit96-diagnostics-help',
    sourceIssue: 'VIT-96',
    capabilityGroup: 'Diagnostics, help, and contract introspection',
    disposition: 'headless_cli_supported',
    commandIds: ['diagnostics.doctor', 'help', 'contract.print'],
    rationale: 'Operational diagnostics and contract discovery are core CLI concerns.',
  },
];

export const CLI_EXIT_CODE_CLASSES: readonly CliExitCodeClassDefinition[] = [
  {
    class: 'success',
    exitCode: 0,
    description: 'The command completed successfully. Warnings may still be present.',
  },
  {
    class: 'validation_error',
    exitCode: 10,
    description: 'Arguments, paths, requested output, or input payload failed validation.',
  },
  {
    class: 'conflict',
    exitCode: 20,
    description: 'Current workspace, document, file, proposal, or repository state is stale or conflicting.',
  },
  {
    class: 'confirmation_required',
    exitCode: 30,
    description: 'The operation requires explicit confirmation and was not confirmed.',
  },
  {
    class: 'unavailable_backend_or_provider',
    exitCode: 40,
    description: 'A required desktop backend, AI provider, or Git backend is unavailable.',
  },
  {
    class: 'unsupported_or_ui_required',
    exitCode: 50,
    description: 'The requested operation is unsupported by CLI or must continue in the desktop UI.',
  },
  {
    class: 'internal_error',
    exitCode: 70,
    description: 'The command failed unexpectedly after validation and preflight.',
  },
];

export const CLI_ERROR_CATALOG: readonly CliErrorCatalogEntry[] = [
  {
    code: 'validation_error',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'Generic validation failure when no narrower code applies.',
  },
  {
    code: 'invalid_arguments',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'Command arguments are missing, malformed, or mutually incompatible.',
  },
  {
    code: 'invalid_output_format',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'The requested output format is not available for this command.',
  },
  {
    code: 'workspace_not_selected',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'No active workspace is available.',
  },
  {
    code: 'workspace_missing',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'The remembered or requested workspace path is unavailable.',
  },
  {
    code: 'invalid_relative_path',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'A workspace-relative path failed syntax validation.',
  },
  {
    code: 'path_outside_workspace',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'A resolved path would escape the active workspace.',
  },
  {
    code: 'unsupported_file_type',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'The target file type is outside the Markdown workspace contract.',
  },
  {
    code: 'file_not_found',
    exitCodeClass: 'validation_error',
    exitCode: 10,
    recoverable: true,
    description: 'The requested workspace-relative file does not exist.',
  },
  {
    code: 'version_conflict',
    exitCodeClass: 'conflict',
    exitCode: 20,
    recoverable: true,
    description: 'The current file or document version differs from the expected version.',
  },
  {
    code: 'dirty_state_conflict',
    exitCodeClass: 'conflict',
    exitCode: 20,
    recoverable: true,
    description: 'Unsaved editor changes block the requested operation.',
  },
  {
    code: 'external_state_changed',
    exitCodeClass: 'conflict',
    exitCode: 20,
    recoverable: true,
    description: 'Workspace, document, file, or repository state changed during preflight.',
  },
  {
    code: 'confirmation_required',
    exitCodeClass: 'confirmation_required',
    exitCode: 30,
    recoverable: true,
    description: 'The operation needs explicit confirmation before it can continue.',
  },
  {
    code: 'operation_cancelled',
    exitCodeClass: 'confirmation_required',
    exitCode: 30,
    recoverable: true,
    description: 'The user cancelled a prompt, handoff, or confirmation.',
  },
  {
    code: 'backend_unavailable',
    exitCodeClass: 'unavailable_backend_or_provider',
    exitCode: 40,
    recoverable: true,
    description: 'The desktop backend or command bridge is unavailable.',
  },
  {
    code: 'provider_not_configured',
    exitCodeClass: 'unavailable_backend_or_provider',
    exitCode: 40,
    recoverable: true,
    description: 'No local AI provider is configured for the requested command.',
  },
  {
    code: 'provider_unavailable',
    exitCodeClass: 'unavailable_backend_or_provider',
    exitCode: 40,
    recoverable: true,
    description: 'The configured local AI provider cannot run successfully.',
  },
  {
    code: 'git_unavailable',
    exitCodeClass: 'unavailable_backend_or_provider',
    exitCode: 40,
    recoverable: true,
    description: 'The Git backend is missing or cannot inspect the workspace.',
  },
  {
    code: 'repository_blocked',
    exitCodeClass: 'conflict',
    exitCode: 20,
    recoverable: true,
    description: 'The repository is in a blocked state such as conflict or detached HEAD.',
  },
  {
    code: 'command_unavailable',
    exitCodeClass: 'unsupported_or_ui_required',
    exitCode: 50,
    recoverable: true,
    description: 'The requested command is not available in the current runtime.',
  },
  {
    code: 'ui_required',
    exitCodeClass: 'unsupported_or_ui_required',
    exitCode: 50,
    recoverable: true,
    description: 'The command must continue in the desktop UI.',
  },
  {
    code: 'unsupported_operation',
    exitCodeClass: 'unsupported_or_ui_required',
    exitCode: 50,
    recoverable: false,
    description: 'The CLI intentionally does not support this operation.',
  },
  {
    code: 'internal_error',
    exitCodeClass: 'internal_error',
    exitCode: 70,
    recoverable: false,
    description: 'Unexpected command failure.',
  },
];

export const CLI_CONFIRMATION_RULES: readonly CliConfirmationRule[] = [
  {
    id: 'confirm-destructive-file',
    kind: 'destructive_file',
    commandIds: ['workspace.file.rename', 'workspace.file.delete', 'markdown.links.create-target'],
    requiredWhen: 'The operation renames, deletes, creates, or overwrites a workspace file.',
    interactiveBehavior: 'Prompt with affected workspace-relative paths and require an explicit yes.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-destructive-mindmap',
    kind: 'destructive_mindmap',
    commandIds: ['mindmap.branch.move', 'mindmap.branch.delete'],
    requiredWhen: 'The operation moves or deletes a branch or subtree.',
    interactiveBehavior: 'Prompt with affected node ids, descendant count, and target path.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-ai-apply',
    kind: 'ai_apply',
    commandIds: ['ai.proposal.apply'],
    requiredWhen: 'The operation applies an AI-generated proposal to editor or file state.',
    interactiveBehavior: 'Prompt with proposal id, base versions, risk flags, and affected files.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-multi-file-change',
    kind: 'multi_file_change',
    commandIds: ['ai.proposal.apply'],
    requiredWhen: 'The operation may affect more than one workspace file or cross-file links.',
    interactiveBehavior: 'Prompt with every affected file and require a second explicit confirmation.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-git-init',
    kind: 'git_init',
    commandIds: ['git.init'],
    requiredWhen: 'The operation creates Git metadata in the workspace.',
    interactiveBehavior: 'Prompt with workspace path and explain that file content is unchanged.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-git-snapshot',
    kind: 'git_snapshot',
    commandIds: ['git.snapshot'],
    requiredWhen: 'The operation stages eligible changes and creates a local commit.',
    interactiveBehavior: 'Prompt with status summary and commit message.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-git-restore',
    kind: 'git_restore',
    commandIds: ['git.restore'],
    requiredWhen: 'The operation restores historical content into the working tree.',
    interactiveBehavior: 'Prompt with source ref, target path, and current file version.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
  {
    id: 'confirm-lossy-markdown-write',
    kind: 'lossy_markdown_write',
    commandIds: ['markdown.serialize', 'workspace.file.save', 'ai.proposal.apply'],
    requiredWhen: 'Compatibility diagnostics report unmapped or lossy Markdown output.',
    interactiveBehavior: 'Prompt with diagnostics and require explicit lossy-save acknowledgement.',
    nonInteractiveBehavior: 'return_confirmation_required',
    bypassFlag: '--confirm-token',
  },
];

export function errorCatalogEntryFor(code: CliErrorCode): CliErrorCatalogEntry {
  const entry = CLI_ERROR_CATALOG.find((candidate) => candidate.code === code);

  if (!entry) {
    return {
      code: 'internal_error',
      exitCodeClass: 'internal_error',
      exitCode: 70,
      recoverable: false,
      description: 'Unknown error code.',
    };
  }

  return entry;
}

export function exitCodeForErrorCode(code: CliErrorCode): CliExitCode {
  return errorCatalogEntryFor(code).exitCode;
}

export function validateCliContractRegistry(): CliContractValidationIssue[] {
  const issues: CliContractValidationIssue[] = [];
  const commandIds = new Set(CLI_COMMANDS.map((command) => command.id));
  const matrixCommandIds = new Set(
    CLI_CAPABILITY_MATRIX.flatMap((entry) => [...entry.commandIds]),
  );
  const confirmationRuleCommandIds = new Set(
    CLI_CONFIRMATION_RULES.flatMap((rule) => [...rule.commandIds]),
  );
  const matrixSourceIssues = new Set(CLI_CAPABILITY_MATRIX.map((entry) => entry.sourceIssue));

  for (const command of CLI_COMMANDS) {
    if (!matrixCommandIds.has(command.id)) {
      issues.push({
        code: 'command_missing_from_matrix',
        message: `${command.id} is registered but not covered by the capability matrix.`,
        commandId: command.id,
      });
    }

    if ((command.confirmationKinds?.length ?? 0) > 0 && !confirmationRuleCommandIds.has(command.id)) {
      issues.push({
        code: 'confirmation_command_missing_rule',
        message: `${command.id} requires confirmation but no confirmation rule references it.`,
        commandId: command.id,
      });
    }
  }

  for (const matrixCommandId of matrixCommandIds) {
    if (!commandIds.has(matrixCommandId)) {
      issues.push({
        code: 'matrix_references_unknown_command',
        message: `${matrixCommandId} is referenced by the capability matrix but is not registered.`,
        commandId: matrixCommandId,
      });
    }
  }

  for (const sourceIssue of REQUIRED_CAPABILITY_SOURCE_ISSUES) {
    if (!matrixSourceIssues.has(sourceIssue)) {
      issues.push({
        code: 'source_issue_missing_from_matrix',
        message: `${sourceIssue} has no capability matrix coverage.`,
        sourceIssue,
      });
    }
  }

  return issues;
}
